/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.16
 * Generated at: 2019-04-19 04:07:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.3.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: \"HelveticaNeue-Light\", \"Helvetica Neue Light\",\r\n");
      out.write("\t\t\"Helvetica Neue\", Helvetica, Arial, \"Lucida Grande\", sans-serif;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tbackground: #333 url(/images/classy_fabric.png);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("\tbackground: #111;\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tmargin: 30px auto;\r\n");
      out.write("\tborder-radius: 0.4em;\r\n");
      out.write("\tborder: 1px solid #191919;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tbox-shadow: 0 5px 10px 5px rgba(0, 0, 0, 0.2);\r\n");
      out.write("\tmargin: 30px auto;\r\n");
      out.write("\ttop:150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form:after {\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\theight: 1px;\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\tleft: 20%;\r\n");
      out.write("\tbackground: linear-gradient(left, #111, #444, #b6b6b8, #444, #111);\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form:before {\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\twidth: 8px;\r\n");
      out.write("\theight: 5px;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\tleft: 34%;\r\n");
      out.write("\ttop: -7px;\r\n");
      out.write("\tbox-shadow: 0 0 6px 4px #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inset {\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("\tborder-top: 1px solid #19191a;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form h1 {\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\ttext-shadow: 0 1px 0 black;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding: 15px 0;\r\n");
      out.write("\tborder-bottom: 1px solid rgba(0, 0, 0, 1);\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form h1:after {\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tleft: 50px;\r\n");
      out.write("\tpointer-events: none;\r\n");
      out.write("\ttransform: rotate(70deg);\r\n");
      out.write("\tbackground: linear-gradient(50deg, rgba(255, 255, 255, 0.15),\r\n");
      out.write("\t\trgba(0, 0, 0, 0));\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label {\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tpadding-bottom: 9px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=text], input[type=password] {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding: 8px 5px;\r\n");
      out.write("\tbackground: linear-gradient(#1f2124, #27292c);\r\n");
      out.write("\tborder: 1px solid #222;\r\n");
      out.write("\tbox-shadow: 0 1px 0 rgba(255, 255, 255, 0.1);\r\n");
      out.write("\tborder-radius: 0.3em;\r\n");
      out.write("\tmargin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label[for=remember] {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tpadding-bottom: 0;\r\n");
      out.write("\tpadding-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".p-container {\r\n");
      out.write("\tpadding: 0 20px 20px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".p-container:after {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\tdisplay: table;\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".p-container span {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tcolor: #0d93ff;\r\n");
      out.write("\tpadding-top: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#inp1 {\r\n");
      out.write("\tpadding: 5px 5px;\r\n");
      out.write("\tborder: 1px solid rgba(0, 0, 0, 0.4);\r\n");
      out.write("\ttext-shadow: 0 -1px 0 rgba(0, 0, 0, 0.4);\r\n");
      out.write("\t/* box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.3), inset 0 10px 10px\r\n");
      out.write("\t\trgba(255, 255, 255, 0.1); */\r\n");
      out.write("\tborder-radius: 0.3em;\r\n");
      out.write("\tbackground: #0184ff;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\talign-content: center;\r\n");
      out.write("\t/* float:right;  */\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin-bottom: 5px;\r\n");
      out.write("\ttext-\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#inp2 {\r\n");
      out.write("\tpadding: 5px 10px;\r\n");
      out.write("\tborder: 1px solid rgba(0, 0, 0, 0.4);\r\n");
      out.write("\ttext-shadow: 0 -1px 0 rgba(0, 0, 0, 0.4);\r\n");
      out.write("\tbox-shadow: inset 0 1px 0 rgba(100, 200, 200, 0.3), inset 0 10px 10px\r\n");
      out.write("\t\trgba(100, 255, 255, 0.1);\r\n");
      out.write("\tborder-radius: 0.3em;\r\n");
      out.write("\tbackground: #0184ff;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\talign-content: center;\r\n");
      out.write("\tfloat: none;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tfont-size: 10px;\r\n");
      out.write("\tmargin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#inp3 {\r\n");
      out.write("\tmargin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#inp4 {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("#header {\r\n");
      out.write("\tbackground-color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<form action=\"index\" method=\"post\" name=\"loginFrm\">\r\n");
      out.write("\t\t<h1>로그인 페이지</h1>\r\n");
      out.write("\t\t<div id=\"inp4\">\r\n");
      out.write("\t\t\t<div id=inp3>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"id\" id=\"id\" placeholder=\"아이디 입력\" size=\"15\"\r\n");
      out.write("\t\t\t\t\t\tmaxlength=\"15\" style=\"color: white;\">\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" name=\"pw\" id=\"pw\" placeholder=\"비밀번호 입력\"\r\n");
      out.write("\t\t\t\t\t\tsize=\"15\" maxlength=\"15\" style=\"color: white;\">\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"inp1\" value=\"로그인\" onclick=\"check()\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"inp1\" value=\"회원가입\"\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='memberJoinMain.jsp'\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<input type=\"button\" name=\"id\" id=\"inp2\" value=\"아이디찾기\"\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='findid.jsp'\"> <input type=\"button\"\r\n");
      out.write("\t\t\t\t\tname=\"pw\" id=\"inp2\" value=\"비밀번호찾기\"\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='findpw.jsp'\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$('#id').focus();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tvar userId = \"\";\r\n");
      out.write("\tvar userPw = \"\";\r\n");
      out.write("\tfunction check() {\r\n");
      out.write("\t\tuserId = $('#id').val();\r\n");
      out.write("\t\tuserPw = $('#pw').val();\r\n");
      out.write("\t\tconsole.log(userId);\r\n");
      out.write("\t\tconsole.log(userPw);\r\n");
      out.write("\r\n");
      out.write("\t\tif (userId == \"\" || userPw == \"\") {\r\n");
      out.write("\t\t\talert(\"아이디와 비밀번호를 입력해 주세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tuserId : userId\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\turl : 'login',\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tconsole.log(\"return : \" + data);\r\n");
      out.write("\t\t\t\tif (userPw == data) {\r\n");
      out.write("\t\t\t\t\t/* session.setAttribute(\"id\",userId);\r\n");
      out.write("\t\t\t\t\tresponse.sendRedirect(\"index.jsp\"); */\r\n");
      out.write("\t\t\t\t\tdocument.loginFrm.submit();\r\n");
      out.write("\t\t\t\t\t/* alert(\"로그인 성공\");\r\n");
      out.write("\t\t\t\t\treturn true; */\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif (userPw != data) {\r\n");
      out.write("\t\t\t\t\talert(\"비밀번호를 확인해 주세요.\");\r\n");
      out.write("\t\t\t\t\twindow.location.href = 'login.jsp';\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(request,status,error) {\r\n");
      out.write("\t\t\t\tconsole.dir(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error); \r\n");
      out.write("\t\t\t\t\t\talert(\"아이디를 확인해주세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
