/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.16
 * Generated at: 2019-04-19 04:08:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Receivedmessage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.3.1.js\"></script>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Receivedmessage.jsp</title>\r\n");
      out.write("<style>\r\n");
      out.write("#portfolios {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 95%;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\toverflow: auto; /* 상품리스트가 많은 경우 스크롤 생성 */\r\n");
      out.write("\tbackground: #333 url(/images/classy_fabric.png);\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".login{\r\n");
      out.write("font-size:16px;\r\n");
      out.write("\tfont-weight : bold;\r\n");
      out.write("\tborder:none;}\r\n");
      out.write("#header{\r\n");
      out.write("border:none;}\r\n");
      out.write("#img1 {\r\n");
      out.write("\twidth: 350px;\r\n");
      out.write("\theight: 150px;\r\n");
      out.write("}\r\n");
      out.write("#header {\r\n");
      out.write("\tbackground-color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div {\r\n");
      out.write("\tborder: 1px solid gray;\r\n");
      out.write("}\r\n");
      out.write(".delete{\r\n");
      out.write("float:right;\r\n");
      out.write("color:red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#messageList, #messageview, #sendmessage {\r\n");
      out.write("\twidth: 498px;\r\n");
      out.write("\theight: 700px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\toverflow: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#list ,#viewbody{\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\tleft:7px;\r\n");
      out.write("\twidth: 479px;\r\n");
      out.write("\tborder: 0px;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\t margin: 5px;  \r\n");
      out.write("\t padding: 10px 20px;  \r\n");
      out.write("\tborder: 1px solid rgba(0, 0, 0, 0.4);\r\n");
      out.write("\ttext-shadow: 0 -1px 0 rgba(0, 0, 0, 0.4);\r\n");
      out.write("\tbox-shadow: inset 0 1px 0 rgba(100, 200, 200, 0.3), inset 0 10px 10px\r\n");
      out.write("\t\trgba(100, 255, 255, 0.1);\r\n");
      out.write("\tborder-radius: 0.3em;\r\n");
      out.write("\tbackground: #0184ff;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\talign-content: center;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tfont-size: 10px;\r\n");
      out.write("\tposition: inherit;\r\n");
      out.write("\ttop:10px;\r\n");
      out.write("}\r\n");
      out.write("#cancle{\r\n");
      out.write("float: left;}\r\n");
      out.write("#m_s_id ,#m_title{\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#m_content {\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\theight: 400px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: \"HelveticaNeue-Light\", \"Helvetica Neue Light\",\r\n");
      out.write("\t\t\"Helvetica Neue\", Helvetica, Arial, \"Lucida Grande\", sans-serif;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tbackground: #333 url(/images/classy_fabric.png);\r\n");
      out.write("}\r\n");
      out.write(".letter{\r\n");
      out.write("color: white;\r\n");
      out.write("text-decoration: none;\r\n");
      out.write("cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"message\">\r\n");
      out.write("\t\t<!-- 받은 편지함 start -->\r\n");
      out.write("\t\t<div id=\"messageList\">\r\n");
      out.write("\t\t\t<h1>\r\n");
      out.write("\t\t\t\t<a class=\"letter\" id=\"receivedmessage\">받은 편지함</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<button id=\"write\">+작성</button>\r\n");
      out.write("\t\t\t\t<a id=\"sendsmessage\" class=\"letter\">보낸 편지함</a>\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\t\t\t<!-- 이 부분에 ajax로 데이터베이스의 제목 가져오기(아이디로) -->\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<div id=\"list\"></div>\r\n");
      out.write("\t\t\t<div id=\"slist\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 받은 편지함 end -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 받은 메시지 상세보기 start -->\r\n");
      out.write("\t\t<div id=\"messageview\">\r\n");
      out.write("\t\t\t<h1>\r\n");
      out.write("\t\t\t\t<span id=\"id\">보낸사람</span>ㅡ <span id=\"sendid\"></span> <button onclick=\"resends()\" id=\"resendss\">답장</button>\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<div id=\"viewbody\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 받은 메시지 상세보기 end -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 보낼 메시지 start -->\r\n");
      out.write("\t\t<div id=\"sendmessage\">\r\n");
      out.write("\t\t\t<h2>새 메시지</h2>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<form action=\"InsertMessage\" method=\"post\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t받는사람:<input type=\"text\" id=\"m_s_id\" size=\"20\" name=\"m_s_id\">\r\n");
      out.write("\t\t\t\t<br> <br> 글 제목:<input type=\"text\" id=\"m_title\"\r\n");
      out.write("\t\t\t\t\tclass=\"message\" size=\"100\" name=\"m_title\"> <br> <br>글\r\n");
      out.write("\t\t\t\t내용:\r\n");
      out.write("\t\t\t\t<textarea id=\"m_content\" name=\"m_content\"></textarea>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<!-- <input type=\"text\" id=\"send\" name=\"send\" value=\"a\" hidden=\"\"> -->\r\n");
      out.write("\t\t\t\t<button id=\"send\">보내기</button>\r\n");
      out.write("\t\t\t\t<button type=\"reset\" id=\"cancel\">취소</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 보낼 메시지 end -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t//첫 화면 모두 숨기기\r\n");
      out.write("\t$(\"#sendmessage\").hide();\r\n");
      out.write("\t$(\"#messageview\").hide();\r\n");
      out.write("\t//작성 클릭시 화면전환\r\n");
      out.write("\t$(\"#write\").click(function() {\r\n");
      out.write("\t$(\"#sendmessage\").show();\r\n");
      out.write("\t$(\"#messageview\").hide();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//receivedmessage 클릭 이벤트\r\n");
      out.write(" $(\"#receivedmessage\").click(function(){\r\n");
      out.write("\t $(\"#id\").html(\"보낸사람\");\r\n");
      out.write("\t $(\"#resendss\").show();\r\n");
      out.write("\t $(\"#messageview\").hide();\r\n");
      out.write("\t $(\"#sendmessage\").hide();\r\n");
      out.write("\t\tvar sid=\"\";\r\n");
      out.write("\t\tvar rs=\"\";\r\n");
      out.write("\t\tvar data = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mlist}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\t\t//rs에 DB의 편지내용 불러온 것 저장\r\n");
      out.write("\t\tfor (var i = 0; i < data.length; i++) {\r\n");
      out.write("\t\t\trs += \"<a id=mtitle style='cursor:pointer'; class='title'>\" + data[i].m_title + \"<a href=delete?title=\"+ data[i].m_title +\"&num=\"+data[i].m_num+\" class=delete>삭제</a></a><hr>\";\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t//list출력\r\n");
      out.write("\t\t$(\"#list\").html(rs); \r\n");
      out.write("\t\t//타이틀 이벤트\r\n");
      out.write("\t\t$(\"a\").click(function() {\r\n");
      out.write("\t\t\tvar a = $(this).html();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype : 'get',//post\r\n");
      out.write("\t\t\t\turl : 'mtitle',\r\n");
      out.write("\t\t\t\tdata : {m_title : a , kind:'a'},\r\n");
      out.write("\t\t\t\tdatatype : 'json',\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tvar datas=JSON.parse(data);\r\n");
      out.write("\t\t\t\t\t$(\"#sendmessage\").hide();\r\n");
      out.write("\t\t\t\t\t$(\"#messageview\").show();\r\n");
      out.write("\t\t\t\t\tsid=$(\"#sendid\").html();\r\n");
      out.write("\t\t\t\t\t$(\"#sendid\").html(datas.m_s_id);\r\n");
      out.write("\t\t\t\t\t$(\"#viewbody\").html(datas.m_content+\"<hr>보낸 시간 : \"+datas.m_s_time);},\r\n");
      out.write("\t\t\t\terror : function(error) {alert(error);}\t});\t});\r\n");
      out.write("\t\t\r\n");
      out.write(" });\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//sendsmessage 클릭 이벤트\r\n");
      out.write("\t$(\"#sendsmessage\").click(function(){\r\n");
      out.write("\t\t$(\"#resendss\").hide();\r\n");
      out.write("\t\t$(\"#id\").html(\"받은사람\");\r\n");
      out.write("\t\t$(\"#messageview\").hide();\r\n");
      out.write("\t\t$(\"#sendmessage\").hide();\r\n");
      out.write("\t\tvar sdata = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${smlist}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\t\tvar rs2 = \"\";\t\r\n");
      out.write("\t\tvar sid2=\"\";\r\n");
      out.write("\t\tfor (var i = 0; i < sdata.length;i++){\r\n");
      out.write("\t\t\trs2 += \"<a id=smtitle style='cursor:pointer'; class='title'>\" + sdata[i].m_title + \"</a><hr>\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//list출력\r\n");
      out.write("\t\t$(\"#list\").html(rs2);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//타이틀 이벤트\r\n");
      out.write("\t\t$(\"a\").click(function() {\r\n");
      out.write("\t\t\tvar a = $(this).html();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype : 'get',//post\r\n");
      out.write("\t\t\t\turl : 'mtitle',\r\n");
      out.write("\t\t\t\tdata : {m_title : a, kind:'b'},\r\n");
      out.write("\t\t\t\tdatatype : 'json',\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tvar datass=JSON.parse(data);\r\n");
      out.write("\t\t\t\t\t$(\"#sendmessage\").hide();\r\n");
      out.write("\t\t\t\t\t$(\"#messageview\").show();\r\n");
      out.write("\t\t\t\t\t$(\"#sendid\").html(datass.m_r_id);\r\n");
      out.write("\t\t\t\t\tsid2=$(\"#sendid\").html();\r\n");
      out.write("\t\t\t\t\t$(\"#viewbody\").html(datass.m_content+\"<hr>보낸 시간 : \"+datass.m_s_time);},\r\n");
      out.write("\t\t\t\terror : function(error) {alert(error);}\t});\t});\r\n");
      out.write("\t});\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t//답장\r\n");
      out.write("\t$(\"#resendss\").click(function(){\r\n");
      out.write("\t\t$(\"#messageview\").hide();\r\n");
      out.write("\t\t$(\"#sendmessage\").show();\r\n");
      out.write("\t\t$(\"#m_s_id\").val($(\"#sendid\").html());\r\n");
      out.write("\t\t$(\"#m_title\").val(\"\");\r\n");
      out.write("\t\t$(\"#m_content\").val(\"\");\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t//보내기\r\n");
      out.write("\t$(\"#send\").click(function(){\r\n");
      out.write("\t\tvar sendid=$(\"#m_s_id\").val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : 'get',//post\r\n");
      out.write("\t\t\turl : 'getid',\r\n");
      out.write("\t\t\tdata : {sendid : sendid},\r\n");
      out.write("\t\t\tdatatype : 'json',\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\talert(data);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(error) {alert(\"메시지 보내기 실패\");}\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
